import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import {
  createPnpmHooksCjs,
  createPnpmfileMergeSnippet,
  createPnpmfileCjs,
  createRootPnpmfileShim,
} from './pnpm-hook-template.js';

export interface IntegrateOptions {
  projectDir: string;
}

export interface IntegrateResult {
  configCreated: boolean;
  configPath: string;
  createdRootPnpmfile: boolean;
  liveDir: string;
  rootPnpmfilePath?: string;
  snippetPath?: string;
}

const liveDirName = '.live-npm';

export async function integrateProject(options: IntegrateOptions): Promise<IntegrateResult> {
  const projectDir = path.resolve(options.projectDir);
  await assertPnpm11Project(projectDir);

  const liveDir = path.join(projectDir, liveDirName);
  await mkdir(liveDir, { recursive: true });
  await writeFile(path.join(liveDir, 'pnpm-hooks.cjs'), createPnpmHooksCjs());
  await writeFile(path.join(liveDir, 'pnpmfile.cjs'), createPnpmfileCjs());
  await writeFile(path.join(liveDir, '.gitignore'), liveGitignore());
  await writeFile(path.join(liveDir, 'README.md'), liveReadme());
  const configPath = path.join(liveDir, 'config.yaml');
  const configCreated = await writeFileIfMissing(configPath, defaultConfigYaml());

  const rootPnpmfilePath = await findRootPnpmfile(projectDir);
  if (!rootPnpmfilePath) {
    const generatedRootPnpmfile = path.join(projectDir, '.pnpmfile.cjs');
    await writeFile(generatedRootPnpmfile, createRootPnpmfileShim());
    return {
      configCreated,
      configPath,
      createdRootPnpmfile: true,
      liveDir,
      rootPnpmfilePath: generatedRootPnpmfile,
    };
  }

  const snippetPath = path.join(liveDir, 'pnpmfile-snippet.cjs');
  await writeFile(snippetPath, createPnpmfileMergeSnippet());
  return {
    configCreated,
    configPath,
    createdRootPnpmfile: false,
    liveDir,
    rootPnpmfilePath,
    snippetPath,
  };
}

async function assertPnpm11Project(projectDir: string): Promise<void> {
  const packageJsonPath = path.join(projectDir, 'package.json');
  const manifest = JSON.parse(await readFile(packageJsonPath, 'utf8')) as { packageManager?: unknown };
  if (typeof manifest.packageManager !== 'string') {
    throw new Error(`${packageJsonPath} must declare packageManager: pnpm@11 or newer.`);
  }
  const match = /^pnpm@(\d+)\./.exec(manifest.packageManager);
  if (!match) {
    throw new Error(`${packageJsonPath} packageManager must use pnpm@11 or newer.`);
  }
  const major = Number(match[1]);
  if (!Number.isInteger(major) || major < 11) {
    throw new Error(`${packageJsonPath} packageManager must use pnpm@11 or newer.`);
  }
}

async function findRootPnpmfile(projectDir: string): Promise<string | undefined> {
  for (const fileName of ['.pnpmfile.mjs', '.pnpmfile.cjs']) {
    const file = path.join(projectDir, fileName);
    if (await exists(file)) {
      return file;
    }
  }
  return undefined;
}

async function writeFileIfMissing(file: string, contents: string): Promise<boolean> {
  if (await exists(file)) {
    return false;
  }
  await writeFile(file, contents);
  return true;
}

async function exists(file: string): Promise<boolean> {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

function defaultConfigYaml(): string {
  return `# live-npm project config.
# Add source packages or workspaces here. Generated runtime files stay under .live-npm.
debounceMs: 200
packages: []
workspaces: []
`;
}

function liveGitignore(): string {
  return `store/
server.json
state.json
*.log
`;
}

function liveReadme(): string {
  return `# live-npm local files

This directory is generated by live-npm. Add \`.live-npm/\` to your project \`.gitignore\` unless you explicitly want to share this local integration.

Edit \`config.yaml\` to declare the source packages or pnpm workspaces that may be resolved through \`live:\` dependency specs.

\`state.json\` is written after pnpm imports live packages. It lets \`live-npm start\` restore live targets after the server restarts.

\`server.json\` is written while \`live-npm start\` is running. pnpm hooks read it to find this project's current local server endpoint.
`;
}
