import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import {
  createPnpmHooksCjs,
  createPnpmfileCjs,
  createRootPnpmfileLiveBlock,
} from './pnpm-hook-template.js';
import { createIntegrationVersionFile, integrationVersionFileName } from './integration-version.js';

export interface IntegrateOptions {
  projectDir: string;
}

export interface IntegrateResult {
  configCreated: boolean;
  configPath: string;
  createdRootPnpmfile: boolean;
  liveDir: string;
  rootPnpmfileAction: 'created' | 'updated' | 'unchanged';
  rootPnpmfilePath?: string;
}

const liveDirName = '.live-npm';
const livePnpmfileStartMarker = '// <live-npm>';
const livePnpmfileEndMarker = '// </live-npm>';

export async function integrateProject(options: IntegrateOptions): Promise<IntegrateResult> {
  const projectDir = path.resolve(options.projectDir);
  await assertPnpm11Project(projectDir);

  const liveDir = path.join(projectDir, liveDirName);
  await mkdir(liveDir, { recursive: true });
  await writeFile(path.join(liveDir, 'pnpm-hooks.cjs'), createPnpmHooksCjs());
  await writeFile(path.join(liveDir, 'pnpmfile.cjs'), createPnpmfileCjs());
  await writeFile(
    path.join(liveDir, integrationVersionFileName),
    `${JSON.stringify(await createIntegrationVersionFile(), null, 2)}\n`,
  );
  await writeFile(path.join(liveDir, '.gitignore'), liveGitignore());
  await writeFile(path.join(liveDir, 'README.md'), liveReadme());
  const configPath = path.join(liveDir, 'config.yaml');
  const configCreated = await writeFileIfMissing(configPath, defaultConfigYaml());

  await assertNoRootPnpmfileMjs(projectDir);
  const rootPnpmfilePath = path.join(projectDir, '.pnpmfile.cjs');
  const rootPnpmfileExists = await exists(rootPnpmfilePath);
  const rootPnpmfileAction = await upsertRootPnpmfileLiveBlock(rootPnpmfilePath);

  return {
    configCreated,
    configPath,
    createdRootPnpmfile: !rootPnpmfileExists,
    liveDir,
    rootPnpmfileAction,
    rootPnpmfilePath,
  };
}

async function assertPnpm11Project(projectDir: string): Promise<void> {
  const packageJsonPath = path.join(projectDir, 'package.json');
  const manifest = JSON.parse(await readFile(packageJsonPath, 'utf8')) as { packageManager?: unknown };
  if (typeof manifest.packageManager !== 'string') {
    throw new Error(`${packageJsonPath} must declare packageManager: pnpm@11 or newer.`);
  }
  const match = /^pnpm@(\d+)\./.exec(manifest.packageManager);
  if (!match) {
    throw new Error(`${packageJsonPath} packageManager must use pnpm@11 or newer.`);
  }
  const major = Number(match[1]);
  if (!Number.isInteger(major) || major < 11) {
    throw new Error(`${packageJsonPath} packageManager must use pnpm@11 or newer.`);
  }
}

async function assertNoRootPnpmfileMjs(projectDir: string): Promise<void> {
  const file = path.join(projectDir, '.pnpmfile.mjs');
  if (await exists(file)) {
    throw new Error(`${file} exists; live-npm integrate does not support .pnpmfile.mjs yet.`);
  }
}

async function upsertRootPnpmfileLiveBlock(rootPnpmfilePath: string): Promise<IntegrateResult['rootPnpmfileAction']> {
  const block = createRootPnpmfileLiveBlock().trimEnd();
  if (!await exists(rootPnpmfilePath)) {
    await writeFile(rootPnpmfilePath, `${block}\n`);
    return 'created';
  }

  const current = await readFile(rootPnpmfilePath, 'utf8');
  const next = upsertMarkedBlock(current, block);
  if (next === current) {
    return 'unchanged';
  }

  await writeFile(rootPnpmfilePath, next);
  return 'updated';
}

function upsertMarkedBlock(contents: string, block: string): string {
  const start = contents.indexOf(livePnpmfileStartMarker);
  const end = contents.indexOf(livePnpmfileEndMarker);
  if (start >= 0 && end >= start) {
    const afterEnd = end + livePnpmfileEndMarker.length;
    return `${contents.slice(0, start)}${block}${contents.slice(afterEnd)}`;
  }

  const prefix = contents.endsWith('\n') ? contents : `${contents}\n`;
  return `${prefix}\n${block}\n`;
}

async function writeFileIfMissing(file: string, contents: string): Promise<boolean> {
  if (await exists(file)) {
    return false;
  }
  await writeFile(file, contents);
  return true;
}

async function exists(file: string): Promise<boolean> {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

function defaultConfigYaml(): string {
  return `# live-npm project config.
# Add source packages or workspaces here. Generated runtime files stay under .live-npm.
debounceMs: 200
packages: []
workspaces: []
`;
}

function liveGitignore(): string {
  return `store/
server.json
state.json
*.log
`;
}

function liveReadme(): string {
  return `# live-npm local files

This directory is generated by live-npm. Add \`.live-npm/\` to your project \`.gitignore\` unless you explicitly want to share this local integration.

Edit \`config.yaml\` to declare the source packages or pnpm workspaces that may be resolved through \`live:\` dependency specs.

\`state.json\` is written after pnpm imports live packages. It lets \`live-npm start\` restore live targets after the server restarts.

\`server.json\` is written while \`live-npm start\` is running. pnpm hooks read it to find this project's current local server endpoint.

\`version.json\` records the live-npm integration version that generated this directory. Re-run \`live-npm integrate\` if live-npm reports that this directory is outdated.
`;
}
